init:
  - git config --global core.autocrlf input

branches:
  only:
    - deploy

environment:
  SIGNTOOL_PATH: 'C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Bin/SignTool.exe'
  SIGN_WIN_CERTIFICATE_FILE: 'C:/foss_ar.pfx'
  SIGN_WIN_CERTIFICATE_PASSWORD:
    secure: jSzK3q/iNcNyh9w93N8O0w==
  AWS_ACCESS_KEY_ID:
    secure: un4e1Apf/PIHv/duLtXtk4j4AIgorOKxvMhxhoUd4N8=
  AWS_SECRET_ACCESS_KEY:
    secure: zP4aGkRtRqZIKZ2tM2q//6dC4SfzKdxDBGTSV3AEbpUnDDco/uMy9ZU1cmVEQigk

cache:
  - "node_modules -> package.json"
  - "src\\node_modules -> src\\package.json"
  - "%APPDATA%\\npm-cache"

install:
  - npm install -g npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - aws s3 cp --region eu-west-1 s3://aluxian/certificates/foss_ar.pfx C:/foss_ar.pfx
  - npm install -g gulp
  - npm install

build_script:
  - node --version
  - npm --version
  - gulp pack:win32:installer
  - gulp pack:win32:portable

test: off

artifacts:
  - path: dist\*

# deploy:
#   - provider: GitHub
#     auth_token:
#       secure: 5HXfg0QXRwPIx6Hjad37cMQvzBXXGnlX31Wnq+S7gFQw5cR9QV8BlgwWlFfuHuu2
#     artifact: dist\*
#     draft: true
#     prerelease: false
#     on:
#       appveyor_repo_tag: true
